application: engineapp-stage-4
version: 2
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /templates
  static_dir: templates
  application_readable: true

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
